### ISSUE TITLE
[Bug] Unsupported operand types in /library/src/Library/Dashboard/SortWidgets.php:166

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/library#90]
An error has been reported in the [WordPress.org Forums](https://wordpress.org/support/topic/critical-error-when-loging-into-wp-admin/) where an unexpected variable type is treated as an array.

Replication steps are unknown, but the full stack trace is as follows:
```
An error of type E_ERROR was caused in line 166 of the file /nas/content/live/kbuk/wp-content/plugins/post-and-page-builder/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php. Error message: Uncaught Error: Unsupported operand types in /nas/content/live/kbuk/wp-content/plugins/post-and-page-builder/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php:166
Stack trace:
#0 /nas/content/live/kbuk/wp-content/plugins/post-and-page-builder/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php(196): Boldgrid\Library\Library\Dashboard\SortWidgets->sortGlobal()
#1 /nas/content/live/kbuk/wp-includes/class-wp-hook.php(290): Boldgrid\Library\Library\Dashboard\SortWidgets->wp_dashboard_setup()
#2 /nas/content/live/kbuk/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/kbuk/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /nas/content/live/kbuk/wp-admin/includes/dashboard.php(123): do_action(‘wp_dashboard_se…’)
#5 /nas/content/live/kbuk/wp-admin/index.php(15): wp_dashboard_setup()
#6 {main}
thrown
```

**Comment by bwmarkle** [comment]
@jessecowens a fix for this has been releases for the library. So far. only Inspirations has been updated and released with the newest library... So if users have multiple BoldGrid plugins installed, the one with the newest library will be used.
